### PR TITLE
Allow build to use sudo without a password

### PR DESCRIPTION
**Pull request by luke-jr**

### CODE REVIEW

**Comment by josephbisch** [comment]
What is the story on this? Is it definitely not going to be merged?

**Comment by devrandom** [comment]
I'm interested in more info.  @josephbisch what is your use case?

**Comment by josephbisch** [comment]
It comes down to basically the same use case as luke-jr had, which is deb packaging. I have this script that I want to run to build Armory reproducibly. I was using the Debian Reproducible Toolchain from the Debian project installed in a chroot created with cowbuilder. It worked and produced a reproducible deb package without using Gitian. Then people said that they wanted it to be wrapped in a Gitian descriptor so that there is a consistent build process for building Armory reproducibly. So I did so and ran into issues with creating the chroot, since root privleges are required. See [this README for examples of the kinds of commands that need to be run](https://github.com/josephbisch/BitcoinArmory/blob/autotools-gitian-0.94/dpkgfiles/make_deb_package.README).

I'm sure there is a more ideal way to be doing it, but I had the script working and then became aware I had to stick it in a Gitian descriptor.

I added the line in this PR to my local gitian-builder and it allowed the build to proceed past the point I was stuck at.

**Comment by devrandom** [comment]
I'm leaning towards enabling this with a flag in the descriptor or a command line flag.

**Comment by josephbisch** [comment]
I think a flag in the descriptor would be best, so that it isn't the end user that would need to do anything extra.

**Comment by droark** [comment]
Hello. I'd also vote for a flag in the descriptor. I understand that root isn't ideal. I suppose it comes down to how badly one wishes to protect users from themselves, or at least possibilities like the hypervisor issue mentioned above. Perhaps a big warning could be thrown up when the flag is encountered, requiring the user to acknowledge what they're doing before proceeding?

**Comment by devrandom** [comment]
Thinking about this further, I think that the ideal solution would have:

* a flag in the descriptor `sudo: true`, that would require a command line flag `--allow-sudo` for security
* disable sudo when the command line flag is not specified

Any takers to implement this?

**Comment by josephbisch** [comment]
I'll make sure this is still something we need (I believe we do) and if so,
I guess I'll be the one to do it. I'm doing other stuff, but I'll be able
to do it in a couple days.

**Comment by kleetus** [comment]
wip on this because I need this to test the gitian ARM builds of Bitcoin.

**Comment by devrandom** [comment]
#122 merged, so closing this

**Pull request closed without merging**
