### PR TITLE
[gverify] print result with bold formatting

### PR DESCRIPTION
**Pull request by MarcoFalke**
Makes it easier to read the result, imo.

### CODE REVIEW

**Comment by devrandom** [comment]
I think this needs either:
* check if stdout is a tty, and disable bolding if not
* and/or, a flag to turn bolding off (and green/red in the future?)

**Comment by MarcoFalke** [comment]
@devrandom I think checking for tty is not sufficient. You'd have to query a db like terminfo or rely on tput, etc. But I consider all of this overkill for this feature.

If you disagree, I'd want to at least separate the output by new lines so it is easier to read.

**Comment by devrandom** [comment]
Well, let's at least make it a flag?

**Comment by MarcoFalke** [comment]
Done

**Comment by MarcoFalke** [comment]
@devrandom

**Comment by MarcoFalke** [comment]
@devrandom Is this good now?

**Pull request merged**
