### PR TITLE
Do not fetch remote when it already there

### PR DESCRIPTION
**Pull request by ultimaweapon**
This will make it easier to integrate Gitian with other tools that already provide git clone functionality (ie Jenkins) so it not double clones.

### CODE REVIEW

**Comment by devrandom** [comment]
Are you sure this is needed?  since it only does a fetch, it's not a full clone and should be fast.

**Comment by ultimaweapon** [comment]
The real problems is not performance but it need to reconnect to the remote repository. If the remote repository is public no problems but if it is private and need to someway to authenticate then it will fail to fetch.

**Comment by devrandom** [comment]
Could you add a note in RELEASE_NOTES that this behavior changed?  some people may be depending on the current behavior when developing on a branch (it will fast forward to the HEAD), and it would be good to let them know of the change.

**Comment by ultimaweapon** [comment]
Updated. Please let me know if you want to change some words since English is not my native language.

**Comment by ultimaweapon** [comment]
Updated.

**Comment by devrandom** [comment]
Thank you!

**Pull request merged**
